### ISSUE TITLE
Theme upload is slow

### ISSUE THREAD

**Issue by sinak** [Shopify/shopify_theme#121]
Uploading an 80KB .scss.liquid file takes on average 2.2 seconds on my quite high speed connection. I have a 60ms latency to the server the `theme upload` is hitting, so I'm assume this is because of the processing that Shopify does on its end to check the file syntax. Is that accurate? Is there any way of speeding things up?

**Comment by csaunders** [comment]
Oh I should probably update this issue.
In phoenix you can control your concurrency for faster uploads:

```yaml
development:
  bucket_size: 40
  refill_rate: 4
```

You can tweak the refill rate as much as you want, but keep in mind that the Shopify refill rate is 2 requests per second. But if your bursts have a decent amount of time in between them you shouldn't run into any problems.
