### ISSUE TITLE
More trouble with Locales

### ISSUE THREAD

**Issue by ajohnh** [Shopify/shopify_theme#128]
I'm unable to download any of these files from an uploaded theme.

A full `theme download` routine results in the following:

'locales/en.default.json' is not in a valid file for theme uploads
Files need to be in one of the following subdirectories: layout/ assets/ config/ snippets/ templates/

Any ideas?

**Comment by csaunders** [comment]
This was never added in the shopify_theme gem.

I'm working on a cross-platform version in go that I plan on making the de-facto Shopify theme synchronization tool. [Try grabbing the latest build and see if that one fixes the issue you are having](http://github.com/csaunders/phoenix/releases/0.0.5).

The configuration files are basically the same so it should "just work"

**Comment by ajohnh** [comment]
Yup, totally works! Looks great. Thanks a lot!
