### ISSUE TITLE
Debugging tool for unused settings variables 

### ISSUE THREAD

**Issue by spuddick** [Shopify/shopify_theme#129]
Not sure if this question is specifically related to shopify_theme but I wasn't sure where else to post. 

I have found that if you happen to use something like `{{settings.header_bg_color}}` in an scss.liquid file, and there is no field for 'header_bg_color' in config/settings.html, the entire corresponding css file is blank. Very difficult to debug since no error message is given. I brought up a similar issue a while back.  But to add to that, I was thinking if during the scss compile, if it notices a settings variable being used in an .scss file which is not preset in config/settings.html, it responds with a warning so you can at least track down where the problem may be.

**Comment by csaunders** [comment]
You can suggest it to https://github.com/csaunders/phoenix though I doubt I'll ever really get around to implementing this kind of feature. There's a decent amount of work that would need to be done to validate that all values are being used (and that values in your templates actually exist in your settings).

**Comment by spuddick** [comment]
Ah yes! I can see the settings values in settings_data.json on the Shopify end. I wasn't aware of that. That is pretty much what I needed.
