### ISSUE TITLE
Can't `Configure`

### ISSUE THREAD

**Issue by nguyenj** [Shopify/shopify_theme#133]
In a new directory, I'm trying to 
`theme configure <API_KEY> <PASSWORD> <STORE>` 
and I'm getting this error 
`'configure': undefined method 'to_yaml' for #<Hash:0x007feeaae61ea0> (NoMethodError)`. 
I'm not sure what I need to do here.

**Comment by csaunders** [comment]
What version of ruby are you running?

**Comment by nguyenj** [comment]
`ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]`

**Comment by whoisbenjamin** [comment]
I'm having the same issue (i think): 

/Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme/cli.rb:50:in `configure': undefined method `to_yaml' for #<Hash:0x007f9a4b48c2f8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/bin/theme:24:in `<top (required)>'
	from /usr/bin/theme:23:in `load'
	from /usr/bin/theme:23:in `<main>'

**Comment by whoisbenjamin** [comment]
I ended up manually writing out the config.yml file, but now receive the following error when trying: theme upload

$ theme upload
/Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme.rb:101:in `config': private method `load' called for Psych:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme.rb:122:in `whitelist_files'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme/cli.rb:191:in `block in local_assets_list'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme/cli.rb:190:in `reject'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme/cli.rb:190:in `local_assets_list'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme/cli.rb:101:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/bin/theme:24:in `<top (required)>'
	from /usr/bin/theme:23:in `load'
	from /usr/bin/theme:23:in `<main>'

**Comment by dommmel** [comment]
The lastest psych (2.0.13) seems to be buggy. Try Version 2.0.0 – works for me.
    
    gem uninstall psych 
    gem install psych -v 2.0.0

**Comment by csaunders** [comment]
I'm unable to replicate the issue. According to the comment by @dommmel you can try using `psych:2.0.x` and should be fine.

I used a Gemfile to try and force `psych:2.0.13` but couldn't replicate the issue.

**Comment by bsehl** [comment]
I've since bought a new machine without any problems. Sure I had a conflict
somewhere or something was outdated.
