### ISSUE TITLE
Theme download does not download all files

### ISSUE THREAD

**Issue by janboden** [Shopify/shopify_theme#140]
When I run the command ``theme download assets/*``, I would suspect that the gem would download all files that are set in Shopify. But it doesn't. It juist downloads the files that I already have in my local project. When I specify the file specifically, it does download the file.

That's pretty annoying when you want to keep your directories clean while building a new template based on a duplicated one.

**Comment by csaunders** [comment]
This project isn't really maintained anymore. I suggest trying to replicate the issue using https://github.com/csaunders/phoenix/releases/tag/0.1.0 instead. Let me know if you are still experiencing the issue.

**Comment by internalfx** [comment]
May I offer an alternative as a gift to the shopify community?

@csaunders We have a few shopify stores and having a solid theme synchronizer is important to us...
I have a project in production which our in-house designer uses. You may remember I wrote an alternate theme sync a while back (When there was discussion about changing the file events library).

This new project fully respects Shopify's API limits. The old one would just hammer the server until it went through.

https://github.com/internalfx/quickshot

**Comment by csaunders** [comment]
Take a look at http://github.com/shopify/phoenix

It also respects the API limits and has configurable levels of concurrency.

**Comment by internalfx** [comment]
Oh wow, I haven't ever tried Go, so I might not be much use on that project.
quickshot is nodejs based. (Although, I use io.js :smile: )

Well...let me ask you then. Is an alternate theme tool something Shopify appreciates, or should I not promote quickshot to other users. (Maybe Shopify wants everyone using phoenix)

My long term plans are to provide local tools inside quickshot. Some items on my shortlist are:

- local scss compiling with the final css being sent to Shopify. Allowing the designer to have many `.scss` files while only loading one in the theme to save load time.
- Access to more advanced templating. Allowing local use of a more powerful language to genereate `.liquid' files with greater automation.

**Comment by csaunders** [comment]
The goal of the go project is to provide a single binary that just works on the various platforms. No ruby/node/io + package manager stuff to get setup and running.

The project is MIT licensed, just give credit where required and do whatever. Best of luck with your project.
