### ISSUE TITLE
Possible to upload changes to two separate themes?

### ISSUE THREAD

**Issue by halleycarleton** [Shopify/shopify_theme#141]
I'm looking for a way to have `theme watch` upload changes to an unpublished theme on a live shop as well as a theme on a dev-shop. Is there any way to accomplish this?

**Comment by csaunders** [comment]
https://github.com/csaunders/phoenix/releases/tag/0.1.0

And run `theme watch --env=production` `theme watch --env=development` in two separate terminal sessions. I don't know if this will work nor what the behaviour will be.

**Comment by halleycarleton** [comment]
Is there more detailed documentation on how to set the environment?

If I run the command in the example I get this:
```
---
:api_key: "-access_token=abracadabra"
:password: "-domain=shopproduction.myshopify.com"
:store: "-env=production"
:theme_id:
```

**Comment by internalfx** [comment]
@halleycarleton quickshot supports this feature

https://github.com/internalfx/quickshot

**Comment by ingedmundo** [comment]
Hey guys! I wrote a blogpost that might be relevant to your interests:

http://blog.crowdint.com/2015/05/08/shopify-theme-staging.html

**Comment by csaunders** [comment]
Seeing as this feature is already supported in a cross-platform tool, I'm going to close this issue.

We will not be implementing the feature for `shopify_theme`
