### ISSUE TITLE
Error: getaddrinfo: Name or service not known (SocketError)

### ISSUE THREAD

**Issue by DannyBen** [Shopify/shopify_theme#147]
I have installed this on Ubuntu 14.04, with Ruby 1.9.3p484  
Have executed `theme configure` with the correct keys.  

When running `theme download` I get this error.

```
/usr/lib/ruby/1.9.1/net/http.rb:763:in `initialize': getaddrinfo: Name or service not known (SocketError)
        from /usr/lib/ruby/1.9.1/net/http.rb:763:in `open'
        from /usr/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
```

I have read the [part of the README](https://github.com/Shopify/shopify_theme/blob/master/README.md#socketerror-or-ssl-certificate-validation-error-on-windows) that offers a solution, and tried that, but it did not work.

I did:
* Copied the `cacert.pem` file to my machine
* Executed `export SSL_CERT_FILE=/path/to/cacert.pem`

But the `theme download` command still gives an error.

A Google search did not offer any help, other than maybe [this page](http://www.subelsky.com/2014/05/fixing-socketerror-getaddrinfo-name-or.html) but I guess that if it is indeed the solution, it needs to be implemented in the gem.

**Comment by csaunders** [comment]
What did you put in for your shops domain?

**Comment by DannyBen** [comment]
My bad...

The README instructions confused me by saying to run `theme configure ..... store_name`
So I used only the store name (the first part of the domain).

Only after reviewing [this line](https://github.com/Shopify/shopify_theme/blob/master/lib/shopify_theme.rb#L138) in the code, I realized I needed a full domain. Seems to work now - apologies and thanks (maybe change the docs from store_name to store_domain to eliminate any chance of confusion?)

**Comment by csaunders** [comment]
https://github.com/Shopify/shopify_theme/commit/c3c6f41f6d76f2ee1ea6f5be5b43dce7c4200444
