### ISSUE TITLE
where to start

### ISSUE THREAD

**Issue by Francisb** [Shopify/shopify_theme#148]
Hi, 

I'm trying to install, but I really don't know where to start, 
I've installed ruby (with the link in the readme ruby 2.2.1-p85 x64), downloaded shopify_theme, after that what to do?
I have no idea, I can do liquid for shopify but wanted to do it from my computer no from shopify interface. 
I'm on windows. 

Never touched to ruby, so I'm very lost, à installation instruction would be very nice for the not initiated to ruby. 

tanks,

**Comment by csaunders** [comment]
[Please use this tool instead](https://github.com/csaunders/themekit)

It has better windows support and _just works_

**Comment by Francisb** [comment]
Thanks, I'll have a look
