### ISSUE TITLE
Support for OAuth token authentication

### ISSUE THREAD

**Issue by gavinballard** [Shopify/shopify_theme#150]
Aware that this project is in maintenance mode, but I just pushed something that came up in the TalkShopify slack to my fork of this repository: https://github.com/Shopify/shopify_theme/compare/master...gavinballard:add_oauth_token_support.

If this is OK to get merged let me know and I will update the PR with tests, README and CHANGELOG updates et cetera.

**Comment by csaunders** [comment]
You could just drop support for the username and password.

You can make authenticated API requests by using the Private Apps Password, so you could just use `password`. Maybe something like this:

```ruby
def self.shopify
  token = config[:access_token] || config[:password]
  headers 'X-Shopify-Access-Token', token
  base_uri "https://#{config[:store]}"
  ShopifyTheme
end
```

I'm pretty sure that would be a reverse compatible change, and would reduce the codepaths we'd need to worry about.

I'd totally accept a pull request on this. Thanks for the work @gavinballard!
