### ISSUE TITLE
'assets/styles.scss' is an unknown file-type, uploading asset as binary

### ISSUE THREAD

**Issue by modermo** [Shopify/shopify_theme#152]
I have theme watch running. Every time I save an asset, I get this:

'assets/styles.scss' is an unknown file-type, uploading asset as binary

The changes are not reflected in the site. Liquid file changes on the other hand however, are reflected

**Comment by csaunders** [comment]
Are you sure your SCSS is valid? The error reporting for that is kinda terrible at the moment.

**Comment by modermo** [comment]
SCSS is definitely valid, as the style.scss.liquid changes are being reflected in the site.

**Comment by csaunders** [comment]
oh... I think it's that the `.scss` file extension isn't being detected as valid. You don't want to be uploading that one to your site. All your changes should be going into the `style.scss.liquid` file.

I assume you are using bourbon or something.

**Comment by modermo** [comment]
Not using Bourbon. 

Why should I be editing the styles.scss.liquid file as opposed to the .scss file? Admittedly, editing the liquid files does implement the change live...

**Comment by csaunders** [comment]
the scss file won't be compiled unless it ends with `.liquid`, hence why the filetype isn't supported.

**Comment by modermo** [comment]
Ok, fair enough. Thanks for the speedy response!
