### ISSUE TITLE
theme bootstrap command issue

### ISSUE THREAD

**Issue by dillonbailey** [Shopify/shopify_theme#153]
Attempting to install bootstrap Timber theme on Shopify store. Steps followed:

1. Register Private App
2. Run below command with necessary details

```
theme bootstrap <api key> <password> the-bside.myshopify.com BSIDE --version=master
Registering BSIDE theme on the-bside.myshopify.com
Could not download theme!
{"errors"=>{"src"=>["is empty"]}}
```

**Comment by csaunders** [comment]
Master versions from Github are slow because it actually builds a zip. Re-running it should cause it work work.

Alternatively, you could use [themekit](http://themekit.cat) which takes care of this and does some graceful retrying.

**Comment by mizuti** [comment]
Try using 
<code>theme bootstrap <api key> <password> the-bside.myshopify.com BSIDE --version='master'</code>

This got mine to work after having the same issue.

**Comment by csaunders** [comment]
v0.2.4 has a fix that should prevent this from coming up again.
