### ISSUE TITLE
Provide callback for when assets complete or if upload times out for some reason

### ISSUE THREAD

**Issue by mpiotrowicz** [Shopify/shopify_theme#154]
cc @cshold @stevebosworth anything else required?

**Comment by cshold** [comment]
I'd just make sure *all* assets are done uploading as multiple can be changed/saved/created at a time. A callback after `theme replace` would be nice too.

**Comment by csaunders** [comment]
https://github.com/csaunders/themekit/pull/51

**Comment by mpiotrowicz** [comment]
we're currently still using the theme gem, any hope of updating it here?

**Comment by csaunders** [comment]
Now that shopify owns themekit, is still still a concern?

**Comment by mpiotrowicz** [comment]
@cshold @stevebosworth

**Comment by stevebosworth** [comment]
If we're committed to actively working on themekit and sunsetting the gem, I'm fine with leaving this as is. if that's still a ways off it would be great to get this available in the gem.

**Comment by csaunders** [comment]
Let's get a milestone rolling on themekit and start adding the missing
features that are blocking you from using it for realz.

On Tue, Sep 1, 2015 at 3:41 PM, Steve Bosworth <notifications@github.com>
wrote:

> If we're committed to actively working on themekit and sunsetting the gem,
> I'm fine with leaving this as is. if that's still a ways off it would be
> great to get this available in the gem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/shopify_theme/issues/154#issuecomment-136837244>
> .
>



-- 
Chris Saunders // Developer @ Shopify

**Comment by csaunders** [comment]
[Here's our milestone.](https://github.com/Shopify/themekit/milestones/Features%20needed%20in%20order%20to%20Sunset%20Shopify%20Theme)

Anything else you can think of?

Should administrative things go in there as well (updating documentation, etc)?

/cc @fredryk

**Comment by cshold** [comment]
:+1: can be closed in favour of going ahead on themekit.
