### ISSUE TITLE
Config not respecting whitelist

### ISSUE THREAD

**Issue by craigmdennis** [Shopify/shopify_theme#156]
I have the following config.yml placed in the root of the Shopify theme

```yml
---
:api_key: [ redacted ]
:password: [ redacted ]
:store: [ redacted ]
:theme_id: [ redacted ]
:whitelist_files:
- assets/all.css.liquid
- assets/all.js
- layout/
- snippets/
- templates/
```

I run a Gulp task to compile all of the Shopify assets which clears the assets directory before copying files back. Regardless of when I set in the `whitelist_files`, `theme watch` always uploads the whole assets directory.

**Comment by csaunders** [comment]
A patch has been merged into master and the next gem release will include it. There's one more thing that needs to go out and a new gem should be available.
