### ISSUE TITLE
Can't do `theme download` to download all files to local

### ISSUE THREAD

**Issue by ajmalafif** [Shopify/shopify_theme#157]
I can't seem to do `theme download` now.

```
theme download
/.rvm/gems/ruby-2.2.0@shopify/gems/shopify_theme-0.0.18/lib/shopify_theme.rb:57:in `asset_list': undefined method `collect' for nil:NilClass (NoMethodError)
```

Even after i ran `bundle install`.

**Comment by csaunders** [comment]
Was your theme configuration working before? The gem hasn't been updated in a while so nothing has changed.

**Comment by ajmalafif** [comment]
@csaunders 

Yeah it was. I ended up using your themekit which works! I don't get on how to use development, staging and live production on config though but i'm settling for one setup for now.

Thanks!
