### ISSUE TITLE
Theme watch not working

### ISSUE THREAD

**Issue by chriswinch** [Shopify/shopify_theme#158]
When running the 'theme watch' command and then making changes to a file, nothing happens.
I can 'theme upload/download' no problem but not 'theme watch'.

Im running ruby 2.2.0p0

Any idea's on what could be causing this?

**Comment by chriswinch** [comment]
I have managed to solve this by using grunt-shopify https://github.com/wilr/grunt-shopify
No idea what caused the theme gem to fail though.

**Comment by csaunders** [comment]
You'll need to provide more information as to what isn't working. I _think_ that you can configure the gem to run through a proxy to provide some more information.

What platform are you using? What output are you getting from `theme watch` when you start the application?

Are you using rbenv? If so, you might have to `rbenv rehash` after you installed the gem.

Without more information I am unable to help you diagnose the problem and fix it in the project.

**Comment by mkandler** [comment]
Quick note for anyone who comes across this post - be sure that in your app settings you give the proper "read and write" permissions.  The default ones will NOT work.  This isn't mentioned in most of the tutorials I've read.

**Comment by abuuzayr** [comment]
@mkandler you are a hero.

**Comment by Humayon** [comment]
facing the following erros
Watching current folder: /Users/h.kabir/Desktop/ShopifyTest
/Library/Ruby/Gems/2.3.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:227:in `watcher': uninitialized constant ShopifyTheme::Cli::FileWatcher (NameError)
Did you mean?  Filewatcher
	from /Library/Ruby/Gems/2.3.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:170:in `watch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
	from /usr/local/bin/theme:22:in `load'
	from /usr/local/bin/theme:22:in `<main>'

**Comment by Jabelriera** [comment]
@Humayon Did you resolve it ? I'm facing the exact same error.

**Comment by tejashweta** [comment]
I'm facing the exact same error. Any Solutions

**Comment by pcosv** [comment]
@Humayon, @Jabelriera, @tejashweta I opened the `cli.rb` file and in the line `FileWatcher.new(Dir.pwd).watch() do |filename, event|` I changed `FileWatcher` to `Filewatcher` and it worked perfect here.

**Comment by talha-phaedra** [comment]
> @Humayon, @Jabelriera, @tejashweta I opened the `cli.rb` file and in the line `FileWatcher.new(Dir.pwd).watch() do |filename, event|` I changed `FileWatcher` to `Filewatcher` and it worked perfect here.

how can we find cli.rb file? i cannot find it in my downloaded theme.
