### ISSUE TITLE
Issue after issue with Windows gem

### ISSUE THREAD

**Issue by JustSteveKing** [Shopify/shopify_theme#167]
I have been search almost *all* day for answers for this.

I ran through the documentation, installed Ruby using **rubyinstaller.org**, installed the correct gem using ```gem install shopify_theme``` then did the usual ```gem update``` and have been having all sorts of issues.

I managed to create my configuration file, *thumbs up* however after that point nothing..

## The first error

```bash
[WARNING] Attempted to create command "local_assets_list" without usage or description. Call desc if you want this method to be available as command or declare it inside a no_commands{} block. Invoked from "C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.24/lib/shopify_theme/cli.rb:197:in `<class:Cli>'".
```

## The second error

```bash
C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.5/lib/httparty.rb:460:in `get'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.24/lib/shopify_theme.rb:140:in `get_index'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.24/lib/shopify_theme/api_checker.rb:35:in `test_connectivity'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.24/lib/shopify_theme/cli.rb:41:in `check'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.24/lib/shopify_theme/cli.rb:137:in `replace'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.24/bin/theme:26:in `<top (required)>'
        from C:/Ruby22-x64/bin/theme:23:in `load'
        from C:/Ruby22-x64/bin/theme:23:in `<main>'
```

I have been searching for ways around this, alternative way in which I could do the same task - however no luck.

**Comment by julionc** [comment]
I guess your OpenSSL version is outdated. Try to update Ruby and OpenSSL

**Comment by csaunders** [comment]
The first one isn't an error, just a warning. It's Thor getting angry because I made something public for testing purposes. I'll get that squelched so it doesn't show up again.

The second one is annoying yeah, and it's been really tricky to figure out. It seems like a lot of people have problems with the gem on Windows.

If you'd like, there is [themekit](https://github.com/shopify/themekit) that is a cross-platform tool that should _just work_. Right now the installation on Windows is still a bit involved vs the Ruby version.

That being said, SSL work out of the box without issues.

**Comment by csaunders** [comment]
I've deployed a new gem version. This one includes a bundled CA certificate that should resolve any SSL errors Windows users have been experiencing. I did the testing on a Windows 8.1 VM to ensure that it behaves the way we expect.

Please let me know if you have any issues.
