### ISSUE TITLE
typo in http://shopify.github.io/shopify_theme/ ?

### ISSUE THREAD

**Issue by skywinder** [Shopify/shopify_theme#175]
I try to instal theme like described in http://shopify.github.io/shopify_theme/

`gem install shopify_theme 48764876` (48764876 - theme id)

and got error 

`ERROR:  Could not find a valid gem '48764876' (>= 0) in any repository`

So, seems syntax should be different.

**Comment by csaunders** [comment]
Yes that's a typo in the documentation. I'll remove that.

**Comment by csaunders** [comment]
https://github.com/Shopify/shopify_theme/commit/a0cd219064a6c46089c27171d7fbd7af4b735b30

**Comment by skywinder** [comment]
:+1: you're awesome, guys!
