### ISSUE TITLE
[minor] command configure  not displayed in help

### ISSUE THREAD

**Issue by skywinder** [Shopify/shopify_theme#178]
theme help

does not provide any info about `configure`

**Comment by csaunders** [comment]
You aren't passing in valid command line arguments. Pass in `-h` or `--help`

**Comment by skywinder** [comment]
Oops sorry. I mean, there is no command `create` ! and `--help` of course, it's typo in description! I update issue.
Related to #177

**Comment by csaunders** [comment]
Create for what? Creating a new blank theme?

If you look at the output for `theme -h` for `configure` you'll see how you should invoke it:

`theme configure API_KEY PASSWORD STORE THEME_ID`

So you'd type something like this to generate your configuration.

`theme configure TokenFromShopify PasswordFromShopify YourShop.myshopify.com themeId(Or Leave absent)`

**Comment by skywinder** [comment]
@csaunders sorry, my mistake. Just look at wrong line! everything great with `help`!
