### ISSUE TITLE
theme download not working

### ISSUE THREAD

**Issue by michael-lynch** [Shopify/shopify_theme#208]
I created a Shopify account, uploaded the [skeleton-theme-master](https://github.com/Shopify/skeleton-theme) as a zip file, updated my version of Ruby to the latest, installed this gem, and ran the `theme configure` command, which worked successfully, as I can see the `config.yml` file. But then when I run `theme download`, nothing happens. `theme watch` also doesn't do anything, though my directory is empty, except for the config file. Am I missing something? Do I need a particular version of Ruby? Or do I need to set a preference in my Shopify account or something?

**Comment by michael-lynch** [comment]
After looking through some of the other issues, I can see that this tool is no longer supported and instead, we should be using http://themekit.com.

https://github.com/Shopify/shopify_theme/issues/196

It would've been a huge help if you had just made that known in the README. Please update this repo so other people don't waste their time troubleshooting a dead tool.

**Comment by lpender** [comment]
`themekit` doesn't work for me...

WTF?
