### ISSUE TITLE
Theme Kit not Detecting New Sections

### ISSUE THREAD

**Issue by elishaolade** [Shopify/shopify_theme#249]
With the theme watch command running, I added a new liquid file to the sections folder of my theme. Theme kit detects any changes made to the header.liquid file that I made earlier. Theme kit shows the updates and deletions of the new section files, but I do not see any of the new sections on the website. 
![Screenshot_2020-08-21 AttackDemo ~ Customize ~ jewels ~ Shopify](https://user-images.githubusercontent.com/12316223/90909829-36594200-e38b-11ea-9ad9-303096456b93.png)

**Comment by tanema** [comment]
This is not the themekit repo. If you are still using this version, please uninstall and move to themekit https://shopify.github.io/themekit/

**Comment by elishaolade** [comment]
Oops. Wrong repository.
