### ISSUE TITLE
Getting No Method Error regardless of config.yml settings

### ISSUE THREAD

**Issue by afxjzs** [Shopify/shopify_theme#36]
I have tried all possible permutations of settings in the config file, i know my API keys and secret are correct. I'm not sure what to use by store url, so i used the exact value from {{store.url}} and that value without the http://. I also used the [store name].myshopify.net url as well. 

Using the url with http:// gives me 

```
/Users/prettyinstant/.rvm/gems/ruby-1.9.2-p290/gems/shopify_theme-0.0.8/lib/shopify_theme.rb:11:in `asset_list': undefined method `collect' for nil:NilClass (NoMethodError)
```

Without the http:// i get:

```
/Users/prettyinstant/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/net/http.rb:644:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
```

I'm pretty certain the other info in my config.yml is correct. I double checked the theme.id and API keys/secret and turned off the password on my store (it's not launched yet)
I installed the gem using `gem install shopify_theme`

Has this gem broken in the last 10 days or am I missing something obvious? Thanks in advance.

**Comment by Cam** [comment]
I had this problem, and found different settings fixed the issue to the ones documented above. My config files look like this:

---
:api_key: 0000000000000000000
:password: 0000000000000000000
:store: store-name.myshopify.com
:theme_id: 

Optionally add the theme number to the ID field.

**Comment by daviddripps** [comment]
I had this issue and removing the "https://" fixed it for me too. The info at http://shopify.github.io/shopify_theme/ is wrong. I'll try to find some time to submit a pull request this week.
