### ISSUE TITLE
Theme watch does not remove files when deleted (OSX)

### ISSUE THREAD

**Issue by markdunkley** [Shopify/shopify_theme#91]
On mavericks when I delete files in finder the theme watch tool fails to remove them from the .myshopify.com store. 

On the current version of the gem

Any thoughts Chris?

**Comment by fumpr** [comment]
How can this be solved? I'm a little bit confused.
Do I need to rewrite some code in order to make the asset file deletion work with theme watch?

**Comment by Moondrop** [comment]
Just ran into to this issue on OSX and with version 0.0.25 of the gem. Is there a solution to this issue currently?
